### ISSUE TITLE
The HLS videos are not visible while playing, showing a black screen on UX (Rpi)

### ISSUE THREAD

**Issue by lk-mlogical** [WebPlatformForEmbedded/Lightning#105]
Hi, 
On Rpi, the player is unable to play HLS videos on the UX browser. The video streaming is not visible while playing, it is showing a black screen. Most of the applications which we are working on are dependent on HLS videos.

**Comment by g-zachar** [comment]
Hi @lk-mlogical ,

video streaming is not part of Lightning, the problem lies most likely in middleware. You should create a Jira ticket providing versions of software you're using, reproduction scenario and - since most likely it's regression - versions of software that introduced the issue.

Best regards

**Comment by thomasfdm** [comment]
Similar to this: 
https://github.com/WebPlatformForEmbedded/Lightning-SDK/issues/51
