### ISSUE TITLE
Entering a state do not contruct the state class

### ISSUE THREAD

**Issue by MattiaPontonioKineton** [WebPlatformForEmbedded/Lightning#139]
Using the debugger I noticed that the method `$enter` is called before the `constructor` and `constructor` is never called.
My goal is to add the event listener before entering a state but only in the context of this state.

![2020-03-25 (2)](https://user-images.githubusercontent.com/58947115/77530173-38c57780-6e91-11ea-87ae-126548204208.png)

**Comment by g-zachar** [comment]
Hi @MattiaPontonioKineton 

That's correct, classes to describe state of a component are not instantiated.

You should think of states as code that modifies or sets the behavior of component. States shouldn't have their own properties but rather modify the component's ones (that's why you have full access to component's context by default). Of course, there are reasonable cases where it would make sense for state to encapsulate some sort of data of its own, but lightning's state machine implementation goes into different direction.

So, addressing your issue, my suggestion is to use component's constructor to initialise your state, or state's `$enter` method if it should be delegated.

Best regards

**Comment by mattiapontonio** [comment]
@g-zachar,
thanks for the clarification.
As a side note, I want to suggest that this causes inconsistency in VS Code type checking. It may drives to error the use of the `class` keyword.
It's a sort of downgrades of the JavaScript features.
Anyway, If it drives to better code It should be followed.
![image](https://user-images.githubusercontent.com/44380480/77672012-a902f480-6f88-11ea-83e8-3692510fe7b2.png)
