### ISSUE TITLE
Iterate over childList: ElementChildList || children: [StateMachineRouter]

### ISSUE THREAD

**Issue by mattiapontonio** [WebPlatformForEmbedded/Lightning#160]
Hello,

What is the best way to iterate over `children`?
For example, in my case, I need to implement a `disable` method on the parent that calls `disable` method on each child.
`disable` is exposed on child type.
REF: https://webplatformforembedded.github.io/Lightning/docs/renderEngine/elements/children

This seem to not work:
```
 disable() {
  this.children.forEach((c, i) => this.childList.getAt(i).disable());
 }
```

**Comment by erikhaandrikman** [comment]
There are multiple ways to iterate over the children, i think you should choose whatever fits your situation best:

I'm not really aware of the rest of the code, my something like the example you've provided should work, also the first param of the callback is the current value 

```
this.children.forEach((c) => {
 c.disable();
});
```

**Comment by mattiapontonio** [comment]
@erikhaandrikman thanks, this is working.
My question is:
If `this.children` is an `Array`, why `this.childList` Does that seem a sort of copy of the functionality?
Anyway, the issue is closable.
Best regards
Mattia

**Comment by erikhaandrikman** [comment]
`this.children` is an accessor of the `Element` class:
https://github.com/WebPlatformForEmbedded/Lightning/blob/2761558c65dee2870bacdb9821c845fc405ccd84/src/tree/Element.mjs#L1655

And is returning the children stored in the childList:
https://github.com/WebPlatformForEmbedded/Lightning/blob/2761558c65dee2870bacdb9821c845fc405ccd84/src/tree/ObjectList.mjs#L32

`this.childList` is returning an instance of `ElementChildList` 
https://github.com/WebPlatformForEmbedded/Lightning/blob/2761558c65dee2870bacdb9821c845fc405ccd84/src/tree/ElementChildList.mjs#L26

which is extending the `ObjectList`

https://github.com/WebPlatformForEmbedded/Lightning/blob/2761558c65dee2870bacdb9821c845fc405ccd84/src/tree/ObjectList.mjs#L24

Since we're working hard on better documentation i really want to encourage you to inspect the Lightning source.
