### ISSUE TITLE
Provide Better Support For Consuming Individual Lightning Modules

### ISSUE THREAD

**Issue by im-bob-loucans** [WebPlatformForEmbedded/Lightning#46]
Currently when I import Lightning as follow in my modules:
```
import lng from "wpe-lightning";

export default class MyComponent extends lng.Component {";
...

```
I end up having to include the entire Lightning library in my final bundle due to the way the index.js and src/lightning.mjs modules come together to export the library as a single object.

It would be helpful if I could specify the imports as follows
```
import Component from "wpe-lightning";

export default class MyComponent extends Component {";
...

```
which will allow build tools like rollup and WebPack to treeshake unused parts of the framework out of the final bundle.

Additionally the src/lightning.mjs has side effects occurring, exposing modules individually will allow me to bypass the creation of the global reference

```
if (Utils.isWeb) {
    window.lng = lightning;
}
```

**Comment by g-zachar** [comment]
Hi @im-bob-loucans 

The initial assumption is to use Lightning as a whole, however you raise a valid concern that some of its modules could be stripped for the purpose of Lightning app, most of them when building a component library.

The side effect you're mentioning is also valid concern, however this cannot be gotten rid of entirely because many of existing apps base their design on it, I guess we could expose both ways for sake of backwards compatibility.
