### ISSUE TITLE
Is it possible to take a screenshot of a frame ?

### ISSUE THREAD

**Issue by salmon-charles** [WebPlatformForEmbedded/Lightning#69]
Hello,

I would like to write tests that generate some components using lighting, and to compare the generated component with the expected one.

So  I need the ability to take a screen shot of what is rendered, maybe by using `glReadPixels` ?

If you have any clues would be great !

Thanks

**Comment by g-zachar** [comment]
Hi @salmon-charles,

I suggest following approach:

1. Set `stage: { canvas2d: true } ` option to enable canvas2d rendering instead of webgl.

2. Use the following snippet in your browser's inspector command line:

```javascript
window.snapshot = () => {
    const canvas = document.getElementsByTagName('canvas')[0];
    const img = document.createElement('img');
    const url = canvas.toDataURL();
    img.src = url;
    document.body.appendChild(img);
}
```

3. Now, whenever you want to create an image, just call `snapshot()` from command line and you should have `<img>` element attached to application's dom tree which you can download.


If you need webgl enabled, I'm afraid it's a lot more tricky, because Lightning's webgl configuration flushes buffers after rendering so you would probably need a modified version of Lightning for that.

**Comment by g-zachar** [comment]
Closing for now, please reopen if still in doubt.
