### ISSUE TITLE
Usage of rrt property

### ISSUE THREAD

**Issue by AndriyShpyra** [WebPlatformForEmbedded/Lightning#74]
Could you please provide more information,  about `rtt` property. 
In which cases it should be used

**Comment by g-zachar** [comment]
Hi @AndriyShpyra,

`rtt` is short alias for `renderToTexture` property (of which both work) that allows you to switch between two rendering modes.

First mode, let's call it *simple mode*, is the default one. In this mode, rendering is similar to how HTML elements are rendered on the page. You could say in this mode that parent and child elements are loosely coupled, for example if your parent has dimensions of 100x100, its child may still be 200x200 and outside bounds of the parent and it will still render properly. Heck, your parent doesn't even need to have dimensions of its own but be just a node in the rendering tree.

When you set `rtt` property for your element, you switch it to second, *advanced mode*. In this mode, children subtree of your elements are bound to the parent's texture. This means that rendering of a subtree will be performed and then the effect of the rendering will then be set as element's texture. You could say that all subtree converges to become the element's texture.

This let's you achieve some things that are hard or not possible in *simple mode* (mostly related to shaders and clipping)

---

Consider an example:

<img width="442" alt="Screenshot 2019-12-05 at 18 07 49" src="https://user-images.githubusercontent.com/52450609/70257251-37f5c200-178a-11ea-8635-dd7d14e7fa09.png">

In this example, there is a parent element with rectangular shape, and a child rectangular element  that is rotated relative to the parent and clipped. This can be achieved easily with this example code:

```javascript
class Example extends lng.Application {
  static _template() {
    return {
      Base: {
        clipping: true,
        x: 100, y: 100,
        w: 300, h: 300,
        rect: true,
        color: 0xff550000,
        Inner: {
          rotation: 0.25,
          w: 300, h: 300,
          src: EXAMPLE_URL,
        },
      }
    }
  }
}
```

However, what if we wanted to rotate parent to achieve this effect:

<img width="507" alt="Screenshot 2019-12-05 at 18 00 22" src="https://user-images.githubusercontent.com/52450609/70256972-c6b60f00-1789-11ea-860b-5a0d90d79d7f.png">

The answer is: in *simple mode* it's not possible to have `rotation` and `clipping` enabled at the same time because of WebGL clipping limitations (mentioned [here](https://webplatformforembedded.github.io/Lightning/docs/renderEngine/elements/rendering)). When rotation is in place, clipping is forcefully disabled.

To work around this issue, we can switch parent element into *advanced mode*, render its contents as a texture and then rotate the parent:

```javascript
class RoundedRectExample extends lng.Application {
  static _template() {
    return {
      Base: {
        rtt: true,
        x: 100, y: 100,
        w: 300, h: 300,
        rect: true,
        color: 0xff550000,
        rotation: 0.25,
        Inner: {
          rotation: 0.25,
          w: 300, h: 300,
          src: EXAMPLE_URL,
        },
      }
    }
  }
}
```
[Full example](https://jsfiddle.net/t1uyk6pv/2/)

Note that in *advanced mode*, clipping is enforced to element's texture dimensions.

---

Another use case has to do with shaders. Let's consider following example:

<img width="539" alt="Screenshot 2019-12-05 at 19 02 59" src="https://user-images.githubusercontent.com/52450609/70261082-fc5ef600-1791-11ea-9b36-9012ffa80761.png">

In this example, we create a base component with embedded image with inverted colors:

```javascript
const diameter = 150;

class TileWrapper extends lng.Component {
  static _template() {
    return {
      Wrapper: {
        Inner: {
          shader: {type: lng.shaders.Inversion},
          w: diameter, h: diameter,
          src: EXAMPLE_URL,
        },
      }
    }
  }
}

class Example extends lng.Application {
  static _template() {
    return {
    Base: {
      x: 50, y: 50, color: 0xff550000, rect: true, w: 500, h: 400,
      T1: {type: TileWrapper},
      T2: {type: TileWrapper, x: diameter + 10},
      }
    }
  }
}
```

The reason this example works in *simple mode* is because `InversionShader` operates only on pixel color and not it's position on the screen. However, if your goal was to achieve something like this:

<img width="542" alt="Screenshot 2019-12-05 at 19 16 27" src="https://user-images.githubusercontent.com/52450609/70261988-c6227600-1793-11ea-9c60-32534e8a8255.png">

you would run into trouble, because in *simple mode* rendering context belongs to root element of the tree and all children inherit its positional rendering properties. They also inherit parent's shader but only if they have none, meaning in *simple mode*, element can have only one active shader at a time.

However, if element has `rtt` property (which means it uses *advanced mode*), it cuts off from rendering context of its parent and creates its own, meaning shaders like `RadialFilterShader` can be applied relative to this element.

[Example code](https://jsfiddle.net/t1uyk6pv/3/)

---
Finally, you can come up with different kind of fancy stuff using `rtt`:

<img width="437" alt="Screenshot 2019-12-05 at 19 50 16" src="https://user-images.githubusercontent.com/52450609/70264330-83af6800-1798-11ea-91c1-8602d12bcb78.png">

[Example code](https://jsfiddle.net/t1uyk6pv/5/)

**Comment by AndriyShpyra** [comment]
@g-zachar , thanks for the answer
