### ISSUE TITLE
Grid component

### ISSUE THREAD

**Issue by MykhailoDz** [WebPlatformForEmbedded/Lightning#77]
With the Lightning framework, we are using lng.components.List Component for Carousel. Do you have a plan to create a Grid component?

Thank you.

**Comment by g-zachar** [comment]
Hey @MykhailoDz,

Actually, we don't plan to develop components in lightning any further because each party has their specific needs. At some point, we'd like to clean up lightning of all the components it has as well. If we come to a point we'd like to develop generic components though, it would be separate library outside of lightning.

Best regards
