### ISSUE TITLE
createSvg vs getSvgTexture

### ISSUE THREAD

**Issue by MattiaPontonioKineton** [WebPlatformForEmbedded/Lightning#88]
In the [Doc ](https://webplatformforembedded.github.io/Lightning/docs/textures/toolbox)is written to use 
`lng.Tools.createSvg(cb, stage, url, w, h)`
Is the right way?
What is `cb` and `stage` and there are available in the App?
Actually I've tried `getSvgTexture`:
```
Svg: {
            x: 10,
            y: 200,
            zIndex: 2,
            color: 0xFFFFFFFF,
            texture: lng.Tools.getSvgTexture('./static/tryit.svg', 300, 300),
        }
```
and it works, following the style of the others methods.
Should be the doc updated?

**Comment by g-zachar** [comment]
Hey @MattiaPontonioKineton,

`getSvgTexture` is more useful as it is a higher level interface that uses `createSvg` under the hood. Documentation could indeed use an update in that regard.

Best regards

**Comment by KadeejaBai** [comment]
@g-zachar What are the parameters 'cb 'and 'stage' ??

**Comment by jhderojasUVa** [comment]
CB is the callback functionSTAGE is an object with the data of the stage (with everything inside, like the canvas and his properties, childrens, etc…) Jesus A. Hernandez de Rojasjhderojas@gmail.com http://macadas.no-ip.infohttp://www.twitter.com/tutihttp://www.flickr.com/jhderojashttps://www.linkedin.com/in/jhderojas/ De: KadeejaBaiEnviado: miércoles, 22 de abril de 2020 15:22Para: WebPlatformForEmbedded/LightningCC: SubscribedAsunto: Re: [WebPlatformForEmbedded/Lightning] createSvg vs getSvgTexture (#88) @g-zachar What are the parameters 'cb 'and 'stage' ??—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.  
	
      
		Libre de virus. www.avg.com

**Comment by mattiapontonio** [comment]
@jhderojasUVa @g-zachar can You please provide an example of how to use that inside a `Lightning.Component` in order to use `lng.Tools.createSvg | Lightning.Tools.createSvg`?
@erikhaandrikman could You please reopen the issue?
